# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Foo
  steps:
  - script:
      echo "Begin a lengthy process..."
      for i in {0..100..10}
      do
        sleep 1
        echo "##vso[task.setprogress value=$i;]Sample Progress Indicator"
      done
        echo "Lengthy process is complete."
    name: DetermineResult

- job: Bar
  dependsOn: Foo
  condition: eq(dependencies.Foo.outputs['DetermineResult.doThing'], 'Yes') #map doThing and check if true
  steps:
   - script: echo "Job Foo ran and doThing is true."
